// AUTO-GENERATED by Tools/EntityGenerator/EntityGenerator.py. Do not edit.
#pragma once

#include "../ORM/Meta.h"
#include "../ORM/Column.h"
{% for f in entity_files %}
#include "../Entities/{{ f }}"
{% endfor %}

{% for e in entities %}
template<> inline void describe_entity<{{ e.name }}>(EntityBuilder<{{ e.name }}>& b)
{
{% for field in e.members %}
    b.field("{{ field.name }}", &{{ e.name }}::{{ field.name }});
{% endfor %}
{% if e.pk %}
    b.primary_key("{{ e.pk }}");
{% endif %}
    b.table("{{ e.name }}");
}

template<> struct Col<{{ e.name }}>
{
{% for field in e.members %}
    static inline ColumnRef<{{ field.inner_type }}> {{ field.name }}{"{{ field.name }}"};
{% endfor %}
};

{% endfor %}
inline void register_all_generated()
{
{% for e in entities %}
    get_entity_meta<{{ e.name }}>();
{% endfor %}
}