// AUTO-GENERATED by Tools/EntityGenerator/EntityGenerator.py. Do not edit.
#pragma once

#include "../ORM/Meta.h"
#include "../ORM/Column.h"
{% for f in entity_files %}
#include "../Entities/{{ f }}"
{% endfor %}

{% for e in entities %}
template<> inline void describe_entity<{{ e.name }}>(EntityBuilder<{{ e.name }}>& b)
{
{% for field in e.members %}
{% if field.is_nav %}
    b.navigation("{{ field.name }}", "{{ field.fk_column }}", "{{ field.inner_type }}", &{{ e.name }}::{{ field.name }});
{% else %}
    b.field("{{ field.name }}", &{{ e.name }}::{{ field.name }}{% if field.max_len %}, {{ field.max_len }}{% endif %});
{% endif %}
{% endfor %}
{% if e.pk %}
    b.primary_key("{{ e.pk }}");
{% endif %}
{% for ix in e.indexes %}
    b.index("{{ ix.name }}", {{ 'true' if ix.unique else 'false' }}, { {% for c in ix.columns %}"{{ c }}"{% if not loop.last %}, {% endif %}{% endfor %} });
{% endfor %}
    b.table("{{ e.name }}");
}

template<> struct Col<{{ e.name }}>
{
{% for field in e.members %}
{% if not field.is_nav %}
    static inline ColumnRef<{{ field.inner_type }}> {{ field.name }}{"{{ field.name }}"};
{% endif %}
{% endfor %}
};

{% endfor %}
inline void register_all_generated()
{
{% for e in entities %}
    get_entity_meta<{{ e.name }}>();
{% endfor %}
}
