syntax = "proto3";
package Protocol;

message C_REGISTER
{
	string name = 1;
	string email = 2;
	string password = 3;
}

message S_REGISTER
{
	bool success = 1;
	string msg = 2;
}

message C_LOGIN
{
	string email = 1;
	string password = 2;
}

message S_LOGIN
{
	bool success = 1;
	string msg = 2;
	string name = 3;
}

message Room
{
	int32 roomId = 1;
	string roomName = 2;
}

message C_CREATE_ROOM
{
	string roomName = 1;
}

message S_CREATE_ROOM
{
	bool success = 1;
	uint32 roomId = 2;
}

message C_GET_ROOM_LIST
{
	
}

message S_GET_ROOM_LIST
{
	bool success = 1;
	repeated Room rooms = 2;
}

message C_ENTER_ROOM
{
	uint32 roomId = 1;
}

message S_ENTER_ROOM
{
	bool success = 1;
	uint32 roomId = 2;
}

message C_EXIT_ROOM
{
	uint32 roomId = 1;
}

message S_EXIT_ROOM
{
	int32 success = 1;
}

message C_UPDATE_NICKNAME
{
	string newNickname = 1;
}

message S_UPDATE_NICKNAME
{
	bool success = 1;
	string msg = 2;
}

message C_DELETE_ACCOUNT
{
}

message S_DELETE_ACCOUNT
{
	bool success = 1;
	string msg = 2;
}

// ==========================
// 채팅 관련
// ==========================

message C_CHAT
{
	string msg = 1;
}

message S_CHAT
{
	string msg = 1;
	string name = 2;
}

message C_SHOUT
{
	string msg = 1;
}

message S_SHOUT
{
	string msg = 1;
	string name = 2;
}

// ==========================
// 친구 추가 관련
// ==========================

message FriendInfo
{
	string email = 1;
	string nickname = 2;
	bool is_online = 3;
}

message C_REQUEST_FRIEND
{
	string email = 1;
}

message S_REQUEST_FRIEND
{
	bool success = 1;
	string msg = 2;
}

message C_ACCEPT_FRIEND
{
	string email = 1;
}

message S_ACCEPT_FRIEND
{
	bool success = 1;
	string msg = 2;
}

message C_REJECT_FRIEND
{
	string email = 1;
}

message S_REJECT_FRIEND
{
	bool success = 1;
	string msg = 2;
}

message C_GET_PENDING_FRIENDS
{
}

message S_GET_PENDING_FRIENDS
{
	bool success = 1;
	repeated FriendInfo pendings = 2;
}

message C_GET_FRIEND_LIST
{
}

message S_GET_FRIEND_LIST
{
	bool success = 1;
	repeated FriendInfo friends = 2;
}

message C_REMOVE_FRIEND
{
	string email = 1;
}

message S_REMOVE_FRIEND
{
	bool success = 1;
	string msg = 2;
}